### ISSUE TITLE
API Blueprint as a source

### ISSUE THREAD

**Issue by walkerscott-svc** [lucybot/api-spec-converter#101]
Does the online tool support API Blueprint as a source?

http://lucybot.github.io/api-spec-converter/

**Comment by bobby-brennan** [comment]
IIRC we were unable to get the API Blueprint parser running successfully in
the browser, so you'll need to use the command line tool for APIBP.

Bobby Brennan
bobby.brennan@gmail.com

**Comment by walkerscott-svc** [comment]
Ok cool, thanks Bobby. Will give it a shot :)
