### ISSUE TITLE
External Schema issue RAML to Swagger_2

### ISSUE THREAD

**Issue by COPUR** [lucybot/api-spec-converter#105]
I can not confirm that external schema usage is supported while converting from RAML to Swagger_2, is that known issue ?

**Comment by IvanGoncharov** [comment]
@COPUR I don't understand the issue 😞 
Can you please provide sample RAML?

**Comment by IvanGoncharov** [comment]
@COPUR I don't understand your problem.
Please either provide sample RAML file or detail description of your problem.

**Comment by IvanGoncharov** [comment]
@COPUR When you will have necessary details please feel free to reopen this issue.
