### ISSUE TITLE
Cannot Convert I/O Doc

### ISSUE THREAD

**Issue by aaronblair** [lucybot/api-spec-converter#118]
The link I was using is:
https://raw.githubusercontent.com/nationbuilder/api_spec/master/spec.json

Maybe there is something non-standard in their file.

**Comment by bobby-brennan** [comment]
At the very least, it looks like it's missing:

```json
{
  "protocol": "rest",
  "basePath": "https://foobar.nationbuilder.com/api/v1/"
}
```

Though I think `foobar` is meant to be replaced with your own subdomain.

You can try copying the spec to a local file and making those changes.

**Comment by aaronblair** [comment]
Yeah, that makes total sense. I didn't realize that the file was missing so much.
