### ISSUE TITLE
Merging RAML and Google Discovery converters

### ISSUE THREAD

**Issue by IvanGoncharov** [lucybot/api-spec-converter#2]
Hi,
I'm also working at the same field and implement [converter](https://github.com/APIs-guru/google-discovery-to-swagger) for Google Discovery [format](https://developers.google.com/discovery/v1/reference/apis).
Also I'm working on RAML [converter](https://github.com/APIs-guru/raml-to-swagger) it's ~80% finished.
If you interested I can merge my code into your project.

P.S. I can't find any license file or file header. Can you specify which license do you use?

**Comment by bobby-brennan** [comment]
This is awesome! Let me know when it's ready and I'll merge. Happy to add you as a collaborator too.

Just added a LICENSE (MIT)

**Comment by IvanGoncharov** [comment]
It took me more that 4 months but I added them eventually :satisfied:
