### ISSUE TITLE
remote repository not found during "npm install"

### ISSUE THREAD

**Issue by holywen** [lucybot/api-spec-converter#32]
```sudo npm install -g api-spec-converter```
npm ERR! git clone --template=/Users/swen/.npm/_git-remotes/_templates --mirror git://github.com/APIs-guru/json-schema-compatibility.git /Users/swen/.npm/_git-remotes/git-github-com-APIs-guru-json-schema-compatibility-git-5fd7aa58: Cloning into bare repository '/Users/swen/.npm/_git-remotes/git-github-com-APIs-guru-json-schema-compatibility-git-5fd7aa58'...
npm ERR! git clone --template=/Users/swen/.npm/_git-remotes/_templates --mirror git://github.com/APIs-guru/json-schema-compatibility.git /Users/swen/.npm/_git-remotes/git-github-com-APIs-guru-json-schema-compatibility-git-5fd7aa58: fatal: remote error: 
npm ERR! git clone --template=/Users/swen/.npm/_git-remotes/_templates --mirror git://github.com/APIs-guru/json-schema-compatibility.git /Users/swen/.npm/_git-remotes/git-github-com-APIs-guru-json-schema-compatibility-git-5fd7aa58:   Repository not found.

**Comment by holywen** [comment]
It seems the "json-schema-compatibility" repo is no longer exists.

**Comment by IvanGoncharov** [comment]
@bobby-brennan Can you publish new version to NPM? It should be `1.2.0`.

@holywen Currently NPM have very outdated version of package ~ 2 month old.
It use outdated version of `google-discovery-to-swagger` which in turn use removed  `APIs-guru/json-schema-compatibility`. We try to publish updated package ASAP.
As temporary work around you can use following command: `npm install -g lucybot/api-spec-converter`

**Comment by holywen** [comment]
Thank you @IvanGoncharov 
but unfortunately there are still some errors.

sudo npm install -g lucybot/api-spec-converter
 
> protagonist@0.20.1 install /usr/local/lib/node_modules/api-spec-converter/node_modules/protagonist
> node-gyp rebuild
'''
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EPERM, utime '/Users/swen/.node-gyp/0.12.7'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/api-spec-converter/node_modules/protagonist
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "lucybot/api-spec-converter"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! protagonist@0.20.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protagonist@0.20.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protagonist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protagonist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
'''

**Comment by IvanGoncharov** [comment]
@holywen It looks like you have problems with `protagonist` package.
Can you please try this command: `npm install protagonist` and attach `npm-debug.log`.
Which OS is you using?

**Comment by bobby-brennan** [comment]
FYI - Pushed 1.2.0 to npm

Bobby Brennan
bobby.brennan@gmail.com

**Comment by holywen** [comment]
@IvanGoncharov I'm using MacOSX 10.10.4 (14E46).
I retried today and this time it works!
Thanks a lot for your quick response!

**Comment by IvanGoncharov** [comment]
@holywen My pleasure.
