### ISSUE TITLE
Support mismatch

### ISSUE THREAD

**Issue by ducin** [lucybot/api-spec-converter#37]
On one hand, you state that supported types are: https://github.com/lucybot/api-spec-converter#supported-types.
On theother hand, the conversion table states, that you can read just few formats and dump them into swagger 2.0: https://github.com/lucybot/api-spec-converter#conversion-table.
IMHO, these information are contradictory...

**Comment by IvanGoncharov** [comment]
Hi @ducin 
We mark format as supported in case if you can download and parse this format and something usefull with it(for e.g. convert to Swagger 2.0).
We don't try to create universal intermediate format which will allow conversation from any format to any format. Instead we think about it as library which aggregate smaller 1to1 conversation libraries and create common facade.
"Conversion Table" is directly after "Supported Types" section so idea is to show which conversions is currently supported.
And as always it open source project which mean that we share our own code.
At the moment me and @bobby-brennan both working on projects which use Swagger 2.0 as internal format. 
__We happily accept any PR which will add conversions to other formats.__

**Comment by IvanGoncharov** [comment]
@bobby-brennan What do you think?

**Comment by bobby-brennan** [comment]
The ultimate goal of this project is to be able to convert between any two specifications, but so far have only had the need to convert to Swagger 2.0.

Agreed it's a little confusing, but we need a spot to list all the types that we deal with so we can link to their documentation etc. Hopefully the conversion table makes it clear what operations are supported and what operations aren't.

**Comment by ducin** [comment]
@bobby-brennan 
> Agreed it's a little confusing
Yep - that's exactly, what I mean.

Do you include external libraries or do you want to implement them on your own? I mean, there are some libraries, which could fulfill the table. I do know about their existence, but I can't assure their quality, haven't checked them yet.

**Comment by bobby-brennan** [comment]
Yeah we prefer to use external libraries where possible. For example, we
use google-discover-to-swagger for converting Google's format to Swagger.
Ivan has made a bunch of contributions to the external libraries to resolve
quality issues.

Feel free to suggest other projects, open bugs, or send pull requests.

Bobby Brennan
bobby.brennan@gmail.com

**Comment by bobby-brennan** [comment]
Edited README to highlight this in bold:

**Currently only supports conversion to Swagger 2.0**
