### ISSUE TITLE
Test is broken due to changes in 'gettyimages.com'

### ISSUE THREAD

**Issue by IvanGoncharov** [lucybot/api-spec-converter#4]
IMHO, problem is little bit deeper than simply update expected 2.0 spec.
I think it better to limit influence of 3rd-party services, and switch on fully synthetic tests, like this:
https://raw.githubusercontent.com/apigee-127/swagger-converter/master/test/input/petstore/index.json

**Comment by bobby-brennan** [comment]
Whoops, this was laziness. I groaned when I put a URL in the test, but it was the easiest route.

I'm going to just pull down the petstore swagger so that the tests only depend on local files.

**Comment by IvanGoncharov** [comment]
Thanks, you library saving me tons of time.
And I try to add some features required for my use case, I will create PR in the end.

Another small issue 'package.json' missing 'mocha' as 'devDependencies'.
I also spotted is that you download spec twice:
https://github.com/lucybot/api-spec-converter/blob/master/index.js#L15
https://github.com/lucybot/api-spec-converter/blob/master/lib/types/swagger_1.js#L31
Is it intentionally behavior?

**Comment by bobby-brennan** [comment]
added mocha and fixed the tests.

The double download is gone now too...now types are wholly responsible for resolving URLs/files, but base-type has some sensible default behavior (i.e. read the file and try to parse it as YAML or JSON)

**Comment by IvanGoncharov** [comment]
Wow, you are fast!
Thank you.
