### ISSUE TITLE
Issue with converting generic type

### ISSUE THREAD

**Issue by zam17** [lucybot/api-spec-converter#81]
Hello!

I'm facing an issue when I'm converting my attached API from Swagger 1.2 to 2.0. The original spec uses List[MapВ«string,objectВ»]. The produced spec includes reference to it ("$ref": "#/definitions/Map┬лstring,object┬╗"), but does not contain the definition itself.

The source and result are attached. Can this be fixed, please?

[issue.zip](https://github.com/lucybot/api-spec-converter/files/123114/issue.zip)

**Comment by IvanGoncharov** [comment]
@zam17 Thank you for providing test sample.
You described two different problems:
1) Missing `MapВ«string,objectВ»` definition. It also missing in 1.2 spec, and converter can't add it.
How `1.2` spec was generated? 
Did you use same framework for it?
2) `Map«string,object»` => `Map┬лstring,object┬╗`. I can't reproduce it, it looks like you converted Unicode into ASCII. Do you running it on Windows?

**Comment by zam17** [comment]
Hi,
1.2 spec I've just downloaded from the swagger that is exposed by our API vendor. I've downloaded it to provide to you, since it's in the internal network.

The second problem is just not a problem, I've copied the output from CMD (yes, I'm using Windows) and the quotes got broken, so do not worry about it.

**Comment by IvanGoncharov** [comment]
@zam17 Simple solution would be to just add `Map«string,object»` manually and use `{}` as value.

I don't want to add workarounds for individual API specs and I didn't experience such problem with any other Swagger 1.2 spec.

**Comment by zam17** [comment]
Ok, will try to add it manually. I agree that certainly such workarounds do not belong to your solution. Thank you for fast response and help!

**Comment by IvanGoncharov** [comment]
My pleasure. You can use http://editor.swagger.io/ for editing Swagger.
