### ISSUE TITLE
Conversion from Swagger 2 to WADL outputs Error: Unable to convert from swagger_2 to wadl

### ISSUE THREAD

**Issue by jfiala** [lucybot/api-spec-converter#98]
I tried to convert the Swagger 2 Petstore API spec to WADL, and I get the following error message:
Error: Unable to convert from swagger_2 to wadl

api-spec-converter -f swagger_2 -t wadl http://petstore.swagger.io/v2/swagger.json

npm\node_modules\api-spec-converter\node_modules\drafter.js\emcc\drafter.nomem.js:1
(function (exports, require, module, __filename, __dirname) { var Module={"ready
":false,"log":(function(text){console.log("drafter.js: "+text)}),"logErr":(funct
ion(text){console.error("drafter.js: "+text)}),"onRuntimeInitialized":(function(
){this.ready=true})};var Module;if(!Module)Module=(typeof Module!=="undefined"?M
odule:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnPr
operty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof win
dow==="object";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require
==="function"&&!ENVIRONMENT_IS_WEB;var ENVIRONMENT_IS_WORKER=typeof importScript
s==="function";var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NOD
E&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["pr
int"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])
Module["printErr"]=func

Error: Unable to convert from swagger_2 to wadl

Does this mean that conversion from Swagger 2 to WADL is not supported?

**Comment by IvanGoncharov** [comment]
> Does this mean that conversion from Swagger 2 to WADL is not supported?

Yes, it's stated in README(second line):
> Currently only supports conversion to OpenAPI(fka Swagger) 2.0 format

If you find/write a JS library for Swagger to WADL conversion please open an issue and we will add support for it.

**Comment by jfiala** [comment]
Thank you for the prompt answer!

**Comment by redtux** [comment]
I know this is an old issue, but I am still having the same problem. It is nice that the README mentions that you (atm – i.e. some years ago!) cannot convert to WADL, but it would be great if `api-spec-converter --help` (and maybe even the error message) would also tell us so. :smiley_cat:
