### ISSUE TITLE
Error when converting from raml

### ISSUE THREAD

**Issue by jfvilas** [lucybot/api-spec-converter#99]
There is a little error when converting references from raml to swagger.

In my company we use nested references in RAML, but the conversión process assumes the references are all set at the same level. For example, if we have a RAML with a reference like this:

"$ref" : "#/schemas/Person"

what we get when converting is:

"#/definitions/#/schemas/Person"

but we should obtain:

"#/definitions/Person"

Thanks in advance.

**Comment by IvanGoncharov** [comment]
@jfvilas I will try to fix it ASAP.
Can you please provide small test file or your entire RAML if it's public.
It will greatly help me because right now I don't fully understand which RAML construct can trigger these bug.

**Comment by jfvilas** [comment]
Please, find attached a simple RAML that causes the abovementioned error.

Thanks in advance.

[JAFV003.txt](https://github.com/lucybot/api-spec-converter/files/207841/JAFV003.txt)

**Comment by IvanGoncharov** [comment]
@jfvilas It looks like this is mistake in your RAML file:
https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-08/raml-08.md#schemas
I implemented the fix and it's very simple just run `npm update`

Did you wrote this file by hand or using some tool?
Is my understanding of RAML correct, or I missed something and your file is correct?

**Comment by jfvilas** [comment]
Yes, i understand schema uses inside raml docs, but the problem here‎ occurs because the use of $ref in json schema, i mean, your library is working right from a raml point of view, but handling json references has nothing to do with raml or swagger, the references in fact can be absolute (like http://somesite.org/schemas...).The real problem arises when usin relative references (like #/schemas or #/definitions).Thanks for your great work and yoyr quick response.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        De: Ivan GoncharovEnviado: viernes, 8 de abril de 2016 20:00Para: lucybot/api-spec-converterResponder a: lucybot/api-spec-converterCC: jfvilasAsunto: Re: [lucybot/api-spec-converter] Error when converting from raml (#99)@jfvilas It looks like this is mistake in your RAML file:
https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-08/raml-08.md#schemas
I implemented the fix and it's very simple just run npm update

Did you wrote this file by hand or using some tool?
Is my understanding of RAML correct, or I missed something and your file is correct?

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by IvanGoncharov** [comment]
@jfvilas Please answer this question:
> Did you wrote this file by hand or using some tool?

**Comment by jfvilas** [comment]
Oops, sorry.We use a home-made tool‎ based on several public community libraries (json library from newtonsoft and yamldotnet).Our raml docs including relative  references are succesfully parsed by Postman.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        De: Ivan GoncharovEnviado: sábado, 9 de abril de 2016 13:58Para: lucybot/api-spec-converterResponder a: lucybot/api-spec-converterCC: jfvilasAsunto: Re: [lucybot/api-spec-converter] Error when converting from raml (#99)@jfvilas Please answer this question:


Did you wrote this file by hand or using some tool?


—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by IvanGoncharov** [comment]
`$ref` is not part of JSON or YAML spec that mean you can't interpret it in a special way.
If you call something RAML it should follow this spec and be processed `from a raml point of view`

> but the problem here‎ occurs because the use of $ref in json schema, i mean, your library is working right from a raml point of view, but handling json references has nothing to do with raml or swagger

RAML inline JSON Schema as a string. It means it separate entity, like a file that embedded into RAML. You can't address something inside string using JSON Reference.

> We use a home-made tool‎ based on several public community libraries (json library from newtonsoft and yamldotnet).

I asked because I have no problem with adding workarounds for commonly used tools.
But I don't want write/maintain code to fix individual specs.

> Our raml docs including relative  references are succesfully parsed by Postman. 

Postman doesn't use JSON Schema at all.

**Comment by IvanGoncharov** [comment]
@jfvilas I will revert this change. If you want to continue using this workaround, here is patch you should apply: https://github.com/APIs-guru/raml-to-swagger/commit/b3d8d19a0e5c1b1bda131a04d6aa8f964361b637

**Comment by IvanGoncharov** [comment]
@jfvilas You can also freeze `raml-to-swagger ` to always be `1.0.1`

**Comment by jfvilas** [comment]
Ok. Thank you‎.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        De: Ivan GoncharovEnviado: sábado, 9 de abril de 2016 14:41Para: lucybot/api-spec-converterResponder a: lucybot/api-spec-converterCC: jfvilasAsunto: Re: [lucybot/api-spec-converter] Error when converting from raml (#99)@jfvilas You can also freeze raml-to-swagger to always be 1.0.1

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub
